language: cpp
fast_finish: true

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libboost1.55-all-dev
      - gcc-6
      - g++-6

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc || true;
      brew link --overwrite gcc;
    fi

install: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-6 ;
      export CXX=g++-6 ;
    fi
  - gcc --version
  - cmake --version
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      cd build-clang
      mkdir build
      cd build
      ./cmake-clang.sh
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mkdir build
      cd build
      cmake ..
    fi

script:  
  - make